const express=require("express")
const { addEmployee, loginEmployee, getEmployeeforSection, getallEmployee } = require("../Controller/employee")
const authentication = require("../middleware/authentication ")
const authorization = require("../middleware/authorization")
const employeeRouter=express.Router()
employeeRouter.post("/",authentication,authorization("ADD_EMPOLYEE"),addEmployee)
employeeRouter.post("/login",loginEmployee)
employeeRouter.get("/",authentication,getallEmployee)
employeeRouter.get("/search_1",authentication,getEmployeeforSection)
module.exports=employeeRouter